# Generated by Django 3.0.6 on 2020-05-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measureluminosity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lumsensor',
            name='latitud',
            field=models.CharField(default=1, max_length=20, verbose_name='latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lumsensor',
            name='longitud',
            field=models.CharField(default=1, max_length=20, verbose_name='longitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lumsensor',
            name='tipoDeTerreno',
            field=models.CharField(default=1, max_length=40, verbose_name='TipoDeTerreno'),
            preserve_default=False,
        ),
    ]
